add_newline = false

[line_break]
disabled = true

[character]
success_symbol = "[>](bold green)"
error_symbol = "[✗](bold red)"

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
style = "italic"
